### PR TITLE
Update Thinking w Xarray data

### PR DESCRIPTION
**Pull request by jukent**
## Change Summary

Adding links and data for "Thinking w Xarray" tutorial

## Checklist

- [ ] Unit tests for the changes exist
- [ ] Tests pass on CI
- [ ] Documentation reflects the changes where applicable

### CODE REVIEW

**Review by kmpaul — APPROVED** [review]
Looks great, @jukent!  Thanks!

**Comment by jukent** [comment]
@kmpaul These changes don't seem to be reflected on the site?

**Comment by kmpaul** [comment]
Yes.  The reason is because you didn't add the new content to the `data/tutorials.yml` file (https://github.com/ncar-xdev/ncar-xdev.github.io/blob/main/data/tutorials.yml).  Instead, you added it directly to the `status/tutorials.md` file (https://github.com/ncar-xdev/ncar-xdev.github.io/blob/main/status/tutorials.md).  The `status/tutorials.md` file gets overwritten every time the website is rebuilt (when it runs the `cli/mktuts.py` utility) based on what is in the `data/tutorials.yml` file.

**Comment by kmpaul** [comment]
I'm sorry I didn't notice that when you submitted the PR.  I just didn't think of it.

**Pull request merged**
